#!/usr/bin/env python3
#
# This script is used to coordinate saving the AD9361 output clock frequency
# and user-inputted MAC address to the u-boot environment as well as writing
# various data to flash memory after successful picozed SDR test runs.
#
# Note that it uses python3 and requires pexpect, pyserial, and picocom to
# be installed.
#
# It also currently assumes the use of a Prologix GPIB-USB controller as well
# as an Agilent 53131A frequency counter used to measure the output clock
# frequency from the AD9361.

import errno
import glob
import os
import sys
import time

import pexpect
import serial

# manufacturer MAC address prefix (Avnet's by default)
MAC_ADDR_OUI = '0002B501'

# model name added to u-boot env and written to device tree
MODEL = 'Zynq PicoZed SDR2 Board'


class GPIBError(Exception):
    """Generic exception for errors when querying the frequency counter."""

class SerialError(Exception):
    """Generic exception for serial device errors."""

class UBootError(Exception):
    """Generic exception for errors when communicating with u-boot."""


def gpib_get_freq(gpib_dev):
    """Get current AD9361 output clock frequency.

    Note that this currently assumes the use of a Prologix GPIB-USB controller
    as well as an Agilent 53131A frequency counter.

    Returns: frequency in HZ
    """
    try:
        s = serial.Serial(gpib_dev)
    except OSError as e:
        if e.errno == errno.ENOENT:
            raise GPIBError("serial device doesn't exist: %s" % gpib_dev)
        raise GPIBError('issue opening serial device: %s: %s' % (gpib_dev, e))

    s.bytesize = serial.EIGHTBITS
    s.parity = serial.PARITY_NONE
    s.stopbits = serial.STOPBITS_ONE
    s.timeout = 2
    s.xonxoff = False
    s.rtscts = False
    s.dsrdtr = False
    s.writeTimeout = 0

    # encode unicode strings to be written into byte strings
    def _write(string):
        s.write(string.encode())

    if not s.isOpen():
        try:
            s.open()
        except Exception as e:
            raise GPIBError(e)

    s.flushInput()
    s.flushOutput()

    # initialize GPIB adapter
    _write('++mode 1\n')
    _write('++auto 1\n')
    _write('++addr 16\n')
    _write('++ver\n')
    gpib_device = s.readline().strip()
    if not gpib_device:
        raise GPIBError('error communicating with GPIB device')

    # confirm communication with frequency counter
    _write('*CLS;*RST;*IDN?\r\n')
    instrument_id = s.readline().strip()
    if not instrument_id:
        raise GPIBError('error communicating with frequency counter')

    # request the current measured frequency
    _write('*RST;*CLS;*SRE 0;*ESE 0;\r\n')
    _write(':STAT:PRES\r\n')
    _write(':DISP:CALC:MATH:STAT OFF\r\n')
    _write(':TRAC SCALE, 1.000000\r\n')
    # we're using channel 1
    _write(":FUNC 'FREQ 1'\r\n")
    _write(':FORM:DATA ASCII\r\n')
    # send expected value and scale so returned value is properly scaled
    _write(':MEASURE:FREQ? 4e7 HZ, 1 HZ\r\n')
    freq = s.readline().strip()
    # re-enable continuous mode for the frequency counter
    _write(':INIT:CONT ON\r\n')
    s.close()
    if not freq:
        raise GPIBError('error querying counter for current frequency')

    freq = int(float(freq))

    # We expect a value close to 40 MHz, error out if it's more than 5 kHz off.
    expected_freq = 40000000
    if abs(freq - expected_freq) > 5000:
        raise GPIBError(
            'Measured frequency too far away from expected frequency (40 MHz): %d Hz' % (freq,))

    return freq


def get_mac_addr():
    """Get MAC address for device.

    Requires that user input the device specific portion.

    Returns: MAC address string in xx:xx:xx:xx:xx:xx format.
    """
    suffix = None
    while suffix is None:
        orig_suffix = input('Enter the remaining 4 character MAC address suffix (e.g. fa34): ')
        # remove all character spacers
        strip_spacers = orig_suffix.maketrans({x: None for x in ':-.'})
        suffix = orig_suffix.translate(strip_spacers)

        # check if it's a valid hex string
        invalid_hex = False
        try:
            int(suffix, 16)
        except ValueError:
            invalid_hex = True

        if len(suffix) != 4 or invalid_hex:
            print('Invalid MAC address suffix: %s' % orig_suffix)
            suffix = None

    mac_addr = MAC_ADDR_OUI + suffix
    mac_addr = '%s%s:%s%s:%s%s:%s%s:%s%s:%s%s' % tuple(mac_addr.lower())
    return mac_addr


def spawn_picocom():
    # UART and GPIB usb serial device paths
    try:
        uart_dev = glob.glob('/dev/serial/by-id/*Silicon_Labs_CP2103_USB_to_UART_Bridge_Controller_0001*')[0]
        gpib_dev = glob.glob('/dev/serial/by-id/*Prologix_Prologix_GPIB-USB_Controller_PX93W44G*')[0]
    except IndexError:
        raise SerialError('UART and/or GPIB serial device nodes missing, make sure cables are plugged in and devices are powered on')

    try:
        p = pexpect.spawnu('picocom --nolock -b 115200 %s' % (uart_dev,))
    except pexpect.exceptions.ExceptionPexpect:
        raise SerialError('picocom is missing, please install it')

    # send output to the terminal and don't reprint input commands
    p.logfile = sys.stdout
    p.setecho(False)

    return p, uart_dev, gpib_dev


def uboot_expect():
    """Pexpect loop to run after the tests complete successfully."""

    spawned = False
    timed_out = False
    warning = False

    # output string specifying that the u-boot command line is ready
    prompt = 'zynq-uboot> '

    def _extract_bytes(l):
        """Extract the size of the file read from u-boot output.

        Returns the file size in bytes.
        """
        # input should consist of a list of strings similar to ['123456', 'bytes', 'read']
        if len(l) != 3 or l[1] != 'bytes' or l[2] != 'read':
            raise UBootError('received unexpected reply when reading file')

        try:
            return int(l[0])
        except ValueError:
            raise UBootError('received unexpected bytes value when reading file')

    def _flash_file(filepath, offset, size, erase=False, timeout=30, mem_location=0x1000000):
        """Erase and write a file to a QSPI flash partition.

        Parameters:
            filepath: path to file to write to partition
            offset: partition offset
            size: partition size
            erase: whether to erase the flash location before writing
            timeout: time to wait while erasing partition (to avoid pexpect timeouts)
            mem_location: external memory location to load file to and from
        """
        # erase memory
        p.sendline('mw 0x%x 0x0 0x%x' % (mem_location, size))
        p.expect(prompt)

        # load file into memory
        p.sendline('fatload mmc 0 0x%x %s' % (mem_location, filepath))
        p.expect('.* bytes read')
        filesize = _extract_bytes(p.after.strip().split()[-3:])
        p.expect(prompt)

        if erase:
            # erase flash partition and write file into it
            p.sendline('sf update 0x%x 0x%x 0x%x' % (mem_location, offset, size))
            p.expect('.* bytes written, .* bytes skipped', timeout=timeout)
        else:
            # we assume flash chips ship pre-erased (as noted in the part's datasheet)
            p.sendline('sf write 0x%x 0x%x 0x%x' % (mem_location, offset, size))
            p.expect('SF: %d bytes @ 0x%x Written: OK' % (size, offset), timeout=timeout)

        p.expect(prompt)

    while 1:
        try:
            if not spawned:
                p, uart_dev, gpib_dev = spawn_picocom()
                spawned = True
            if not timed_out:
                p.expect('Terminal ready')
                print('Waiting for u-boot output, please power on or reset the device')
            i = p.expect(['ALL TESTS PASSED', 'TESTS FAILED'], timeout=1800)
            if i == 1:
                p.expect('Hit any key')
                print('Tests failed, restarting loop...')
                continue
            p.expect(prompt)

            # run GPIB query to determine actual ad9361 reference clock
            # frequency and save it to the u-boot environment
            try:
                freq = gpib_get_freq(gpib_dev)
            except GPIBError:
                print('\nError querying frequency counter, restarting loop...')
                continue
            p.sendline('setenv ad9361_ext_refclk 0x%x' % (freq,))
            p.expect(prompt)
            p.sendline('setenv model %s' % (MODEL,))
            p.expect(prompt)

            p.sendline('sf probe')
            p.expect('SF: Detected N25Q256A')
            p.expect(prompt)

            # write files to flash
            _flash_file('flash/BOOT.BIN', 0x0, 0xe0000)
            _flash_file('uImage', 0x100000, 0x500000)
            _flash_file('devicetree.dtb', 0x600000, 0x20000)
            _flash_file('Card-Filesystem-Repair/uramdisk.image.gz', 0x620000, 0xce0000, timeout=60)
            _flash_file('flash/system.bit', 0x1300000, 0xd00000, timeout=60)

            # set MAC address
            print()
            mac_addr = get_mac_addr()
            p.sendline('setenv ethaddr %s' % mac_addr)
            p.expect(prompt)
            p.sendline('saveenv')
            p.expect(prompt)
            print('\n\n############################################')
            print('Board ready for shipping')
            print('Power off and insert next module for testing')
            print('############################################')
            timed_out = False
        except pexpect.TIMEOUT:
            if not timed_out:
                print('\nTimed out waiting for u-boot output, restarting loop...')
            timed_out = True
            continue
        except KeyboardInterrupt:
            # restart the expect loop if the user hits Ctrl-C
            print('Got keyboard interrupt, restarting loop...')
            timed_out = True
            continue
        except pexpect.exceptions.EOF as e:
            if spawned:
                print('\nSerial device closed, restarting loop...')
                spawned = False
            time.sleep(1)
            continue
        except SerialError as e:
            if not warning:
                print(e)
                warning = True
            time.sleep(1)
            continue
        except UBootError as e:
            print('\nError running U-Boot command: %s, restarting loop...' % e)
            time.sleep(1)
            continue
    p.close()

if __name__ == '__main__':
    while 1:
        try:
            uboot_expect()
        except KeyboardInterrupt:
            print()
            pass
        except UnicodeDecodeError:
            # we don't care about unicode decoding issues, e.g. if linux starts
            # booting and dumps odd characters into the output stream
            pass
