#!/bin/sh

cd /usr/local/src

if [ -d iio-oscilloscope ] ; then
  cd ./iio-oscilloscope
  git pull
  cd ..
else
  git clone https://github.com/analogdevicesinc/iio-oscilloscope.git
fi

if [ -d fru_tools ] ; then
  cd ./fru_tools
  git pull
  cd ..
else
  git clone https://github.com/analogdevicesinc/fru_tools.git
fi

if [ -d iio-cmdsrv ] ; then
  cd iio-cmdsrv
  git pull
  cd ..
else
  git clone https://github.com/analogdevicesinc/iio-cmdsrv.git
fi


